#!/bin/sh
#
# @name NetDrones Humblebee V1
#
# @type Quadrotor
#
# @maintainer Rakuto Furutani <rakuto@netdrones.ai>
#

. ${R}etc/init.d/airframes/10088_humblebee

# EKF2: Vision position and heading
param set-default EKF2_EV_DELAY 0
